version: '3'
services:
  www:
    restart : always
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - "./php:/var/www/html"
    ports:
      - 80:80

  db:
    image: mysql:latest
    restart : always
    environment:
      MYSQL_DATABASE : "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD : "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart : always
    ports:
     - 8001:80
    environment:
      PMA_HOST : db
      PMA_PORT : 3306