services:
  pg-database:
    image: postgres:17.1
    container_name: postgresql_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432 # [HOST_PORT]:[CONTAINER_PORT], use port 5433 to avoid conflict if 5432 already been used
    environment:
      - POSTGRES_DB=db  # Change to target database
      - POSTGRES_USER=user # Change to target user
      - POSTGRES_PASSWORD=localdevpw 
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "db", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5

  pyspark-notebook:
    image: quay.io/jupyter/pyspark-notebook # Pull image from quay.io not Docker Hub
    container_name: jupyter_notebook
    restart: always
    environment:
      - JUPYTER_TOKEN=localdevpw   # Jupyter Notebook Password/Token, use this to login
    ports:
    - "9999:8888"
    volumes:
      - ./notebook:/home/jovyan/work
    
volumes:
  db-data:  # create volume to preserve the data in database